bug 134: Regressions and more when building newlib.
git-svn-id: http://ellcc.org/svn/ellcc/trunk@779 82857169-6e38-49d7-aaa8-07fb558f12fc

diff --git a/ellcc/regrtest b/ellcc/regrtest
--- a/ellcc/regrtest
+++ b/ellcc/regrtest
@@ -287,6 +287,13 @@ failCparse() {
   fi
   failTest "$2" perl ./multitest.pl ./ecc in/$1
 }
+failCparse_special() {
+  if [ "$3" = "" ]; then
+    echo "failparse $1: failparse takes three arguments"
+    exit 4
+  fi
+  failTest "$3" perl ./multitest.pl ./ecc $2 in/$1
+}
 failCparse_march() {
   if [ "$3" = "" ]; then
     echo "failparse_march $1: failparse_march takes three arguments"
@@ -346,7 +353,7 @@ testCparse t0048.c
 testCparse t0049.c
 failCparse t0050.c "K&R argument promotion"
 testCparse_special_march sparc -S t0051.c
-testCparse_special -O0 t0052.c
+failCparse_special -O0 t0052.c "Nested GEP"
 
 # is K&R built?
 use_kandr=false
