Changes to build gnu tools, libraries.
git-svn-id: http://ellcc.org/svn/ellcc/branches/reset@2153 82857169-6e38-49d7-aaa8-07fb558f12fc

diff --git a/gnu/makegnu b/gnu/makegnu
--- a/gnu/makegnu
+++ b/gnu/makegnu
@@ -5,22 +5,6 @@ prefix=`cd ..; pwd`
 targets=`cat ../targets`
 targetlist=`echo $targets | sed -e "s/ /,/g"`
 bin=`cd ../bin; pwd`
-# To build for the x86 with libecc:
-#cc=$bin/i686-elf-ecc
-#cxx=$bin/i686-elf-e++
-
-# To build with the hosted ecc and host libraries:
-#cc=$bin/ecc
-#cxx=$bin/e++
-
-# To build with the clang and host libraries:
-#cc=$bin/clang
-#cxx=$bin/clang++
-
-# To build with the host compiler:
-cc=gcc
-cxx=g++
-
 
 # Parse options.
 install=0
@@ -41,10 +25,23 @@ if [ $install -eq 0 ] ; then
  mkdir obj
 fi
 
+#
+# qemu
+#
+
 cd obj
 
-# Symbolic links to create.
-linklist= # "addr2line ar ld nm objcopy objdump ranlib readelf size strings strip"
+# To build for the x86 with libecc:
+#cc=$bin/i386-elf-ecc
+#cxx=$bin/i386-elf-e++
+
+# To build with the hosted ecc and host libraries:
+#cc=$bin/ecc
+#cxx=$bin/e++
+
+# To build with the host compiler:
+cc=gcc
+cxx=g++
 
 qemu_target_list="i386-softmmu x86_64-softmmu arm-softmmu microblaze-softmmu mips-softmmu mipsel-softmmu \
     ppc-softmmu ppc64-softmmu"
@@ -84,7 +81,23 @@ else
   cd ..
 fi
 
-packages="binutils gdb"
+#
+# binutils
+#
+
+# To build for the x86 with libecc:
+#cc=$bin/i386-elf-ecc
+#cxx=$bin/i386-elf-e++
+
+# To build with the hosted ecc and host libraries:
+cc=$bin/ecc
+cxx=$bin/e++
+
+# To build with the host compiler:
+#cc=gcc
+#cxx=g++
+
+packages="binutils"
 for p in $packages; do
 if [ $install -eq 0 ] ; then
   echo Making package $p for $targets
@@ -119,16 +132,86 @@ else
 #    echo make install-html failed
 #    exit 1
 #  fi
-  for target in $targets ; do
-    for tool in $linklist ; do
-      (cd $prefix/bin; ln -sf ecc-$tool $target-$tool)
-    done
-  done
   cd ..
 fi
 done
 
 cd ..
+
+#
+# gdb
+#
+
+# To build for the x86 with libecc:
+#cc=$bin/i386-elf-ecc
+#cxx=$bin/i386-elf-e++
+
+# To build with the hosted ecc and host libraries:
+#cc=$bin/ecc
+#cxx=$bin/e++
+
+# To build with the host compiler:
+cc=gcc
+cxx=g++
+
+cd obj
+
+packages="gdb"
+for p in $packages; do
+if [ $install -eq 0 ] ; then
+  echo Making package $p for $targets
+  mkdir $p
+  cd $p
+  ../../src/$p/configure CC=$cc CXX=$cxx --enable-64-bit-bfd --enable-targets=$targetlist \
+    --program-prefix=ecc- --prefix=$prefix/lib --bindir=$prefix/bin --datadir=$prefix/lib/share
+  if [ $? -ne 0 ] ; then
+    echo configure for $p failed
+    exit 1
+  fi
+
+  sed -e "s:/.*/gnu/src/missing ::g" Makefile > tmp$$
+  mv tmp$$ Makefile
+
+  make
+  if [ $? -ne 0 ] ; then
+    echo make for $p failed
+    exit 1
+  fi
+  cd ..
+else
+  cd $p
+  make install
+  if [ $? -ne 0 ] ; then
+    echo make install failed
+    exit 1
+  fi
+# RICH: gnu-oids.texi is missing. FIXME
+#  make install-html
+#  if [ $? -ne 0 ] ; then
+#    echo make install-html failed
+#    exit 1
+#  fi
+  cd ..
+fi
+done
+
+cd ..
+
+#
+# as for all targets
+#
+
+# To build for the x86 with libecc:
+#cc=$bin/i386-elf-ecc
+#cxx=$bin/i386-elf-e++
+
+# To build with the hosted ecc and host libraries:
+cc=$bin/ecc
+cxx=$bin/e++
+
+# To build with the host compiler:
+#cc=gcc
+#cxx=g++
 
 cd obj
 cd binutils
